name: amenity
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  image_picker: ^1.0.4
  get: ^4.6.6
  flutter_riverpod: ^2.4.6
  firebase_core: ^2.22.0
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.13.0
  firebase_storage: ^11.5.0
  cached_network_image: ^3.3.0
  badges: ^3.1.2
  uuid: ^4.2.1
  custom_rating_bar: ^2.0.5
  flutter_rating_bar: ^4.0.1
  image: ^4.1.3
  flutter_svg: ^2.0.9
  universal_io: ^2.2.2
  file_picker: ^6.1.1
  flutter_slidable: ^3.0.1
  flutter_stripe: ^10.0.0
  http: ^1.1.2
  hooks_riverpod: ^2.4.9
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.1.0
  cloud_functions: ^4.6.0
  stylish_bottom_bar: ^1.0.3
  flutter_swipe_button: ^2.1.1+1
  location: ^5.0.3
  card_swiper: ^3.0.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_map: ^6.1.0
  sticky_grouped_list: ^3.1.0
  material_segmented_control: ^5.0.0
  flutter_credit_card: ^4.0.1
  group_button: ^5.3.4
  latlng: ^1.0.0
  banner_listtile: ^2.3.0
  blobs: ^2.0.0
  equatable: ^2.0.5
  queen_validators: ^1.0.1
  share_plus: ^7.2.1
  swipe_deck: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/
    - assets/card_badges/
    - assets/home_icons/
    - assets/categoryImages/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
